---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redis"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: {{.Values.broker.strategyType}}
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-ngx
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{.Values.broker.image}}
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          resources:
            limits:
              cpu: {{.Values.broker.resources.limits.cpu}}
              memory: {{.Values.broker.resources.limits.memory}}
            requests:
              cpu: {{.Values.broker.resources.requests.cpu}}
              memory: {{.Values.broker.resources.requests.memory}}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
              subPath: data
      volumes:
        - name: redis-storage
          {{- if .Values.broker.persistentVolumeClaim.enabled }}
          persistentVolumeClaim:
            claimName: "redis-pvc"
          {{- else }}
          emptyDir: {}
          {{- end }}

---
{{- if .Values.broker.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "redis-pvc"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - {{ index .Values.broker.persistentVolumeClaim.accessModes 0 }}
  resources:
    requests:
      storage: {{.Values.broker.persistentVolumeClaim.size}}
  {{- if .Values.broker.persistentVolumeClaim.storageClassName }}
  storageClassName: {{.Values.broker.persistentVolumeClaim.storageClassName}}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: "broker"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: redis
