---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gotenberg"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/component: gotenberg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-ngx
        app.kubernetes.io/component: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: {{.Values.gotenberg.image}}
          command:
            - "gotenberg"
            - "--chromium-allow-list"
            - "file:///tmp/.*"
            - "--chromium-disable-javascript"
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: "gotenberg"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: gotenberg
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: gotenberg
