---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  strategy:
    type: {{.Values.postgres.strategyType}}
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-ngx
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{.Values.postgres.image}}
          env:
            - name: POSTGRES_DB
              value: "paperless"
            - name: POSTGRES_USER
              value: "paperless"
            - name: POSTGRES_PASSWORD
              value: "paperless"
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources:
            limits:
              cpu: {{.Values.postgres.resources.limits.cpu}}
              memory: {{.Values.postgres.resources.limits.memory}}
            requests:
              cpu: {{.Values.postgres.resources.requests.cpu}}
              memory: {{.Values.postgres.resources.requests.memory}}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgres-storage
          {{- if .Values.postgres.persistentVolumeClaim.enabled }}
          persistentVolumeClaim:
            claimName: "postgres-pvc"
          {{- else }}
          emptyDir: {}
          {{- end }}

---
{{- if .Values.postgres.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "postgres-pvc"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - {{ index .Values.postgres.persistentVolumeClaim.accessModes 0 }}
  resources:
    requests:
      storage: {{.Values.postgres.persistentVolumeClaim.size}}
  {{- if .Values.postgres.persistentVolumeClaim.storageClassName }}
  storageClassName: {{.Values.postgres.persistentVolumeClaim.storageClassName}}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: "postgres"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: postgres
