---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tika"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/component: tika
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-ngx
        app.kubernetes.io/component: tika
    spec:
      containers:
        - name: tika
          image: {{.Values.tika.image}}
          ports:
            - containerPort: 9998
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: {{.Values.tika.resources.limits.cpu}}
              memory: {{.Values.tika.resources.limits.memory}}
            requests:
              cpu: {{.Values.tika.resources.requests.cpu}}
              memory: {{.Values.tika.resources.requests.memory}}

---
apiVersion: v1
kind: Service
metadata:
  name: "tika"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: tika
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: tika
